account/urls.py
from django.urls import path
from account.views import *
app_name = "account"

urlpatterns = [
    path('', home_view, name="home"),
    path('register/', register_view, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('account/<user_id>/', account_view, name="view"),
    path('account/<user_id>/edit/', edit_account_view, name="edit"),
    path('search/', account_search_view, name="search"),
    path('contect/', contect_view, name="contect"),
    path('aboutus/', about_us_view, name="about_us"),
]

kmarket/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace='account')),
    path('question/', include('question.urls', namespace='question')),
    path('notification/', include('notification.urls', namespace='notification')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),

    #     path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
    #          name='password_reset_done'),

    #     path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
    #          name='password_reset_confirm'),
    #     path('password_reset/', auth_views.PasswordResetView.as_view(),
    #          name='password_reset'),

    #     path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
    #          name='password_reset_complete'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset/password_reset.html",success_url=reverse_lazy('password_reset_done')), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset/password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset/password_reset_form.html",success_url=reverse_lazy('password_reset_complete')), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset/password_reset_done.html"), name="password_reset_complete"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

question/urls.py
from django.urls import path
from question.views import *
app_name = "question"

urlpatterns = [
    path('', all_question_view, name="all_question"),
    path('add_question/', add_question, name="add_question"),
    path('remove_question/<question_id>',
         remove_question, name="remove_question"),
    path('search/', question_search_view, name="search"),
    path('your_answer/', your_answer_view, name="your_answer"),
    path('<question_id>/', question_view, name="question"),
    path('<question_id>/add_answer/', add_answer, name="add_answer"),
    path('<question_id>/edit/', edit_question_view, name="edit_question"),
    path('<question_id>/question_like/',
         like_question_view, name="question_like"),
    path('<question_id>/like/', like_answer_view, name="like"),
    path('<question_id>/answer_edit/<answer_id>',
         edit_answer_view, name="edit_answer"),
    path('<question_id>/remove_answer/<answer_id>',
         remove_answer, name="remove_answer"),
]

question/forms.py
from django.forms import ModelForm
from question.models import *
from django import forms
from question.models import Question, Answer


class AddQuestionForm(ModelForm):
    class Meta:
        model = Question
        field = ('title', 'question', 'auth')
        exclude = ['Question']


class AddAnswerForm(ModelForm):
    class Meta:
        model = Answer
        field = ('answer', 'question', 'auth')
        exclude = ['Answer']


class QuestionUpdateForm(ModelForm):
    class Meta:
        model = Question
        field = ('title', 'question', 'auth')
        exclude = ['Question']


class AnswerUpdateForm(ModelForm):
    class Meta:
        model = Answer
        field = ('answer', 'question', 'auth')
        exclude = ['Answer']

question/views.py
from account.models import Account
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from question.models import Answer, Like, Question, LikeQuestion
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from account.models import Account
from question.forms import AddAnswerForm, AddQuestionForm, QuestionUpdateForm, AnswerUpdateForm
# Create your views here.


def all_question_view(request, *args, **kwargs):
    context = {}
    questions = Question.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(questions, 6)
    try:
        question = paginator.page(page)
    except PageNotAnInteger:
        question = paginator.page(1)
    except EmptyPage:
        question = paginator.page(paginator.num_pages)
    context['questions'] = questions
    context['question'] = question
    context['search'] = True
    context['question_search'] = True
    return render(request, 'question/home.html', context)


def question_view(request, *args, **kwargs):
    context = {}
    user = request.user
    question_id = kwargs.get("question_id")
    # answer_id = kwargs.get("answer_id")
    if user.is_authenticated:
        try:
            question = Question.objects.get(id=question_id)
            answer = Answer.objects.filter(question=question)
            account = Account.objects.get(id=user.id)
            answer_owner = answer.filter(auth=account)
        except Question.DoesNotExist:
            return HttpResponse("That question doesn't exist.")

        if question:
            context['question'] = question

        if answer:
            context['answer'] = answer

        is_self = True
        is_friend = False
        if user.is_authenticated and question.auth != user:
            is_self = False
        elif not user.is_authenticated:
            is_self = False

        context['answer_owner'] = answer_owner
        context['is_self'] = is_self
        context['is_friend'] = is_friend
        context['BASE_URL'] = settings.BASE_URL
        context['each'] = True
    return render(request, 'question/eachquestion.html', context)


def like_question_view(request, *args, **kwargs):
    user = request.user
    question_id = kwargs.get("question_id")
    if user.is_authenticated:
        if request.POST:
            id = request.POST.get('question_like')
            obj = Question.objects.get(id=id)

            if user in obj.like.all():
                obj.like.remove(user)
            else:
                obj.like.add(user)

            liked, created = LikeQuestion.objects.get_or_create(
                auth=user, question_id=id)

            if not created:
                if liked.value == 'Like':
                    liked.value = 'unlike'
                else:
                    liked.value = 'like'
            liked.save()
    return redirect('question:question', question_id)


def like_answer_view(request, *args, **kwargs):
    user = request.user
    question_id = kwargs.get("question_id")
    if user.is_authenticated:
        if request.POST:
            id = request.POST.get('answer_like')
            obj = Answer.objects.get(id=id)

            if user in obj.like.all():
                obj.like.remove(user)
            else:
                obj.like.add(user)

            liked, created = Like.objects.get_or_create(auth=user, ans_id=id)

            if not created:
                if liked.value == 'Like':
                    liked.value = 'unlike'
                else:
                    liked.value = 'like'
            liked.save()
    return redirect('question:question', question_id)


def add_question(request, *args, **kwargs):
    context = {}
    user = request.user
    auth = Account.objects.get(id=user.id)
    if user.is_authenticated:
        form = AddQuestionForm()
        if request.POST:
            form = AddQuestionForm(request.POST)
            if form.is_valid():
                obj = form.save(commit=False)
                obj.auth = auth
                obj.save()
                return redirect('account:view', user_id=user.id)
            else:
                context['form'] = form
    context['CRUD'] = True
    return render(request, 'question/add_question.html', context)


def remove_question(request, *args, **kwargs):
    context = {}
    user = request.user
    question_id = kwargs.get("question_id")
    if user.is_authenticated:
        try:
            question = Question.objects.get(id=question_id)
        except Exception as e:
            return HttpResponse("Question not exists!!")

        context['question'] = question
        if request.POST:
            question.delete()
            return redirect('account:view', user_id=user.id)
    context['CRUD'] = True
    return render(request, 'question/remove_question.html', context)


def add_answer(request, *args, **kwargs):
    context = {}
    user = request.user
    question_id = kwargs.get("question_id")
    auth = Account.objects.get(id=user.id)
    question = Question.objects.get(id=question_id)
    if user.is_authenticated:
        form = AddAnswerForm()
        if request.POST:
            form = AddAnswerForm(request.POST)
            if form.is_valid():
                obj = form.save(commit=False)
                obj.auth = auth
                obj.question = question
                obj.save()
                return redirect('question:question', question_id=question.id)
            else:
                context['form'] = form
    context['CRUD'] = True
    return render(request, 'question/add_answer.html', context)


def remove_answer(request, *args, **kwargs):
    context = {}
    user = request.user
    answer_id = kwargs.get("answer_id")
    question_id = kwargs.get("question_id")
    if user.is_authenticated:
        try:
            answer = Answer.objects.get(id=answer_id)
        except Exception as e:
            return HttpResponse("Answer not exists!!")

        context['answer'] = answer
        if request.POST:
            answer.delete()
            return redirect('question:question', question_id=question_id)
    context['question_id'] = question_id
    context['CRUD'] = True
    return render(request, 'question/remove_answer.html', context)


def question_search_view(request, *args, **kwargs):
    context = {}
    if request.method == "GET":
        search_query = request.GET.get("q")
        if len(search_query) > 0:
            search_results = Question.objects.filter(
                title__icontains=search_query)
            user = request.user
            questions = []
            for question in search_results:
                questions.append(question)
            print(questions)
            context['questions'] = questions
    context['question_search'] = True
    context['search'] = True
    return render(request, "question/search_results.html", context)


def edit_question_view(request, *args, **kwargs):
    user = request.user
    if not request.user.is_authenticated:
        return redirect("account:login")
    question_id = kwargs.get("question_id")
    question = Question.objects.get(pk=question_id)
    context = {}
    if request.POST:
        form = QuestionUpdateForm(
            request.POST, request.FILES, instance=question)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.auth = user
            obj.save()
            return redirect("question:question", question_id=question.pk)
        else:
            form = QuestionUpdateForm(request.POST, instance=question,
                                      initial={
                                          "id": question.pk,
                                          "title": question.title,
                                          "question": question.question,
                                      }
                                      )
            context['form'] = form
    else:
        form = QuestionUpdateForm(request.POST, instance=question,
                                  initial={
                                      "id": question.pk,
                                      "title": question.title,
                                      "question": question.question,
                                  }
                                  )
        context['form'] = form
    context['CRUD'] = True
    return render(request, "question/edit_question.html", context)


def edit_answer_view(request, *args, **kwargs):
    user = request.user
    if not request.user.is_authenticated:
        return redirect("account:login")
    question_id = kwargs.get("question_id")
    answer_id = kwargs.get("answer_id")
    question = Question.objects.get(pk=question_id)
    answer = Answer.objects.get(pk=answer_id)
    context = {}
    if request.POST:
        form = AnswerUpdateForm(
            request.POST, request.FILES, instance=answer)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.question = question
            obj.auth = user
            obj.save()
            return redirect("question:question", question_id=question.pk)
        else:
            form = AnswerUpdateForm(request.POST, instance=answer,
                                    initial={
                                        "id": answer.pk,
                                        "answer": answer.answer,
                                    }
                                    )
            context['form'] = form
    else:
        form = AnswerUpdateForm(request.POST, instance=answer,
                                initial={
                                    "id": answer.pk,
                                    "answer": answer.answer,
                                }
                                )
        context['form'] = form
    context['CRUD'] = True
    return render(request, "question/edit_answer.html", context)

question/templates/question/eachquestion.html
{% extends 'account/main.html' %}
{% load static %}
{% block content %}
<style>
  .each{
    border-radius: 25px;
    height: -webkit-fit-content;
    height: -moz-fit-content;
    height: fit-content;
    background-color: rgba(0, 0, 0, 0.4);
    -webkit-backdrop-filter: blur(10px);
    backdrop-filter: blur(10px);
    align-items: center;
    width: 35cm;
    height: 18cm;
    margin-top: 0.8cm;
    margin-left: 2.8cm;
    padding-bottom: 3.5em;
    margin-bottom:10px;
  }
  .button {
    font-family: sans-serif;
    font-weight: bold;
    font-size: medium;
    border: none;
    padding: 1em;
    outline: none;
    color: black;
    text-transform: uppercase;
    font-style: 1.2em;
    position: relative;
    z-index: 1;
    cursor: pointer;
    background: none;
    text-shadow: 3px 3px 10px rgba(0, 0, 0, 0.45);
    margin:10px 585px;
  }
  .button:before,
  .button:after {
    position: absolute;
    top: 50%;
    left: 50%;
    border-radius: 10em;
    transform: translateX(-50%) translateY(-50%);
    width: 88%;
    height: 98%;
    content: "";
    z-index: -2;
    background-size: 400% 400%;
    background: white;
  }
  .button:before {
    filter: blur(10px);
    transition: all 0.25s ease;
    -webkit-animation: pulse 10s infinite ease;
    animation: pulse 10s infinite ease;
  }
  .button:after {
    filter: blur(0.3px);
  }
  button:hover:before {
    width: 90%;
    height: 100%;
  }
  .table-scroll tbody {
    border-radius: 15px;
    display: block;
    position: relative;
    width: 100%;
    height: 5cm;
    padding-bottom: 2.5cm;
    overflow-y: scroll;
    border-top: 1px solid rgba(0, 0, 0, 0.2);
  }

  .table-scroll tr {
    width: 100%;
    display: flex;
  }

  .table-scroll td,
  .table-scroll th {
    flex-basis: 100%;
    flex-grow: 2;
    display: block;
    padding: 1rem;
    text-align: center;
    overflow: hidden;
    /*align-items: center;*/
  }

  /* Other options */

  .table-scroll.small-first-col td:first-child,
  .table-scroll.small-first-col th:first-child {
    flex-basis: 20%;
    flex-grow: 1;
  }

  .table-scroll tbody tr:nth-child(2n) {
    background-color: rgba(130, 130, 170, 0.1);
  }

  .body-half-screen {
    max-height: 50vh;
  }

  .small-col {
    flex-basis: 10%;
  }

  .table-scroll ::-webkit-scrollbar {
    width: 6px;
  }
  .table-scroll ::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
  }
  .table-scroll ::-webkit-scrollbar-thumb {
    -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
  }
  .table-scroll {
    display: block;
    width: 33cm;
    margin-left: 1cm;
    padding-top: 1cm;
    border-spacing: 0;
    height:50px;
  }

  .table-scroll thead {
    border-radius: 15px;
    position: relative;
    display: block;
    width: 100%;
    overflow-y: hidden;
    background-color: rgba(130, 130, 170, 0.1);
  }
  .table2 {
    font-size: 20;
    display: block;
    margin-left:100px;
    border-radius: 15px;
  }
  .table2 tr {
    background-color: rgba(130, 130, 170, 0.1);
  }
  .table th,
  td {
    border-radius: 15px;
    padding: 10px;
  }
  a{
  color:pink;
  font-weight:bold;
  text-decoration:none;
  }
  .b1 {
    border: none;
    background: none;
    cursor: pointer;
    margin: 0;
    padding: 4px;
    color: white; 
  }
</style>

<div class="each">
  <table>
    <tr>
      <th>
        <button class="button"><a href="{% url 'question:add_answer' question_id=question.id %}" style="text-decoration:none;color:black;"
        >Add Answer</a
        ></button>
      </th>
    </tr>
  </table>
  <br />
  <div class="table2">
    <table>
      <tr>
        <td>Title: </td>
        <td>{{question.title}}</td>
      </tr>
      <tr>
        <td>Question: </td>
        <td>{{question.question}}</td>
      <tr>
        <td>Question By: </td>
        <td>{{question.auth}}</td>
      </tr>
      <tr>
        <td>Likes: </td>
        <td>
          <form
                  action="{% url 'question:question_like' question_id=question.id %}"
                  method="POST"
          >
            {% csrf_token %}
            <input type="hidden" name="question_like" value="{{question.id}}" />
            {% if user not in question.like.all %}
            <button class="b1"><i class="far fa-thumbs-up fa-2x"></i></button>
            {% else %}
            <button class="b1"><i class="fas fa-thumbs-up fa-2x"></i></button>
            {% endif %}
            <strong>{{question.like.all.count}} likes</strong>
          </form>
        </td>
      </tr>
      {% if is_self %}
      <td>
        <a href="{% url 'question:edit_question' question_id=question.id %}">Update Question</a>
      </td>
      <td>
        <a href="{% url 'question:remove_question' question_id=question.id %}"
        >Remove Question</a>
      </td>
      {% endif %}
      </tr>
    </table>
  </div>
  <br />
  <table class="table-scroll small-first-col;table-view:fixed;">
    <thead>
    <tr>
      <th>Answer</th>
      <th>Answer by</th>
      <th>Likes</th>
    </tr>
    </thead>
    <tbody>
    {% for ans in answer %}
    <tr>
      <th>{{ans.answer}}</th>
      <th>{{ans.auth}}</th>
      <th>
        <form
                action="{% url 'question:like' question_id=question.id %}"
                method="POST"
        >
          {% csrf_token %}
          <input type="hidden" name="answer_like" value="{{ans.id}}" />
          {% if user not in ans.like.all %}
          <button class="b1"><i class="far fa-thumbs-up fa-2x"></i></button>
          {% else %}
          <button class="b1"><i class="fas fa-thumbs-up fa-2x"></i></button>
          {% endif %}
        </form>
        <strong>{{ans.like.all.count}} likes</strong>
      </th>  
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

question/templates/question/remove_answer.html
{% extends 'account/main.html' %} {% load static %} {% block content %}

<style type="text/css">
  .remove {
    text-align: center;
    align-items: center;
    border-radius: 25px;
    height: -webkit-fit-content;
    height: -moz-fit-content;
    height: fit-content;
    /* display: inline-flex; */
    background-color: rgba(0, 0, 0, 0.4);
    -webkit-backdrop-filter: blur(10px);
    backdrop-filter: blur(10px);
    align-items: center;
    /* padding: 2.4cm 5.5cm; */
    width: 11cm;
    height: 7cm;
    margin-top: 3.5cm;
    margin-left: 14.4cm;
    padding-bottom: 3.5em;
  }
  .remove label {
    font-family: sans-serif;
    color: white;
    font-weight: bold;
    font-size: 20px;
    position: relative;
    cursor: pointer;
    white-space: nowrap;
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 50px 30px;
  }
  button {
    font-family: sans-serif;
    font-weight: bold;
    font-size: medium;
    border: none;
    padding: 1em;
    outline: none;
    color: black;
    text-transform: uppercase;
    font-weight: 700;
    font-style: 1.2em;
    letter-spacing: 0em;
    position: relative;
    z-index: 1;
    cursor: pointer;
    background: none;
    text-shadow: 3px 3px 10px rgba(0, 0, 0, 0.45);
    margin-left: 20px;
    margin-top: 30px;
  }
  button:before,
  button:after {
    position: absolute;
    top: 50%;
    left: 50%;
    border-radius: 10em;
    transform: translateX(-50%) translateY(-50%);
    width: 100%;
    height: 95%;
    content: "";
    z-index: -2;
    background-size: 100% 100%;
    background: white;
  }
  button:before {
    filter: blur(10px);
    transition: all 0.25s ease;
    -webkit-animation: pulse 10s infinite ease;
    animation: pulse 10s infinite ease;
  }
  button:after {
    filter: blur(0.3px);
  }
  button:hover:before {
    width: 105%;
    height: 115%;
  }
  input {
    align-items: center;
    margin-left: 130px;
    margin-top: 30px;
    width: 40%;
  }
  h2 {
    padding-top: 20px;
  }
</style>

<div class="remove">
  <form
    action="{% url 'question:remove_answer' question_id=question_id answer_id=answer.id %}"
    method="POST"
  >
    {% csrf_token %}
    <h2>Do You want to delete your answer!!!</h2>
    <button type="submit">Yes</button>
    <button type="button" value="Go back" onClick="javascript:history.go(-1);" >No</button>
  </form>
</div>
{% endblock %}

question/templates/question/remove_question.html
{% extends 'account/main.html' %} {% load static %} {% block content %}

<style type="text/css">
  .remove {
    text-align: center;
    align-items: center;
    border-radius: 25px;
    height: -webkit-fit-content;
    height: -moz-fit-content;
    height: fit-content;
    /* display: inline-flex; */
    background-color: rgba(0, 0, 0, 0.4);
    -webkit-backdrop-filter: blur(10px);
    backdrop-filter: blur(10px);
    align-items: center;
    /* padding: 2.4cm 5.5cm; */
    width: 11cm;
    height: 7cm;
    margin-top: 3.5cm;
    margin-left: 14.4cm;
    padding-bottom: 3.5em;
  }
  .remove label {
    font-family: sans-serif;
    color: white;
    font-weight: bold;
    font-size: 20px;
    position: relative;
    cursor: pointer;
    white-space: nowrap;
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 50px 30px;
  }
  button {
    font-family: sans-serif;
    font-weight: bold;
    font-size: medium;
    border: none;
    padding: 1em;
    outline: none;
    color: black;
    text-transform: uppercase;
    font-weight: 700;
    font-style: 1.2em;
    letter-spacing: 0em;
    position: relative;
    z-index: 1;
    cursor: pointer;
    background: none;
    text-shadow: 3px 3px 10px rgba(0, 0, 0, 0.45);
    margin-left: 25px;
    margin-top: 50px;
  }
  button:before,
  button:after {
    position: absolute;
    top: 50%;
    left: 50%;
    border-radius: 10em;
    transform: translateX(-50%) translateY(-50%);
    width: 100%;
    height: 95%;
    content: "";
    z-index: -2;
    background-size: 100% 100%;
    background: white;
  }
  button:before {
    filter: blur(10px);
    transition: all 0.25s ease;
    -webkit-animation: pulse 10s infinite ease;
    animation: pulse 10s infinite ease;
  }
  button:after {
    filter: blur(0.3px);
  }
  button:hover:before {
    width: 105%;
    height: 115%;
  }
  .b1 {
    margin-left: 185px;
  }
  input {
    margin-left: 140px;
    margin-top: 30px;
    width: 40%;
    align-items: center;
  }
  h2 {
    padding-top: 20px;
  }
</style>

<div class="remove">
  <form
    action="{% url 'question:remove_question' question_id=question.id %}"
    method="POST"
  >
    {% csrf_token %}
    <h2>Do You want to delete your Question!!!</h2>
    <button type="submit">Yes</button>
    <button type="button" value="Go back" onClick="javascript:history.go(-1);" >No</button>
  </form>
</div>
{% endblock %}

question/templates/question/your_answer.html
{% extends 'account/main.html' %}
{% load static %}
{% block content %}

<style type="text/css">
	.main{
    border-radius: 25px;
    height: -webkit-fit-content;
    height: -moz-fit-content;
    height: fit-content;
    background-color: rgba(0, 0, 0, 0.4);
    -webkit-backdrop-filter: blur(10px);
    backdrop-filter: blur(10px);
    align-items: center;
    width: 35cm;
    height: 15cm;
    margin-top: 0.8cm;
    margin-left: 2.8cm;
    /*padding-bottom: 3.5em;*/
    margin-bottom:10px;
  }
  .table-scroll tbody {
    border-radius: 15px;
    display: block;
    position: relative;
    width: 100%;
    height: 5cm;
    padding-bottom: 2.5cm;
    overflow-y: scroll;
    border-top: 1px solid rgba(0, 0, 0, 0.2);
  }

  .table-scroll tr {
    width: 100%;
    display: flex;
  }

  .table-scroll td,
  .table-scroll th {
    flex-basis: 100%;
    flex-grow: 2;
    display: block;
    padding: 1rem;
    text-align: center;
    float: left;
    overflow: hidden;
    /*align-items: center;*/
  }

  /* Other options */

  .table-scroll.small-first-col td:first-child,
  .table-scroll.small-first-col th:first-child {
    flex-basis: 20%;
    flex-grow: 1;
  }

  .table-scroll tbody tr:nth-child(2n) {
    background-color: rgba(130, 130, 170, 0.1);
  }

  .body-half-screen {
    max-height: 50vh;
  }

  .small-col {
    flex-basis: 10%;
  }

  .table-scroll ::-webkit-scrollbar {
    width: 6px;
  }
  .table-scroll ::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
  }
  .table-scroll ::-webkit-scrollbar-thumb {
    -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
  }
  .table-scroll {
    display: block;
    width: 33cm;
    margin-left: 1cm;
    padding-top: 1cm;
    border-spacing: 0;
    height:50px;
  }

  .table-scroll thead {
    border-radius: 15px;
    position: relative;
    display: block;
    width: 100%;
    overflow-y: hidden;
    background-color: rgba(130, 130, 170, 0.1);
  }
  .table2 {
    font-size: 20;
    display: block;
    margin-left:100px;
    border-radius: 15px;
  }
  .table2 tr {
    background-color: rgba(130, 130, 170, 0.1);
  }
  .table th,
  td {
    border-radius: 15px;
    padding: 10px;
  }
  .table-scroll ::-webkit-scrollbar {
    width: 6px;
  }
  .table-scroll ::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
  }
  .table-scroll ::-webkit-scrollbar-thumb {
    -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
  }
  h1{
  	padding-top: 30px; 
  	margin-left: 50px;
  }
  a{
  color:pink;
  font-weight:bold;
  text-decoration:none;
  }
  table{
    table-layout:fixed;
    display: block;
    position: relative;
  }
  .b1 {
    border: none;
    background: none;
    cursor: pointer;
    margin: 0;
    padding: 4px;
    color: white; 
  }
</style>

<div class="main">
	<h1>Your Answer</h1>
	<table class="table-scroll small-first-col" style="">
		<thead>
			<tr>
				<th style="padding-right: 100px; width: 0px;">Answer</th>
				<th>In This Question</th>
				<th>Likes</th>
				<th>Answerd By</th>
        <th>Update</th>
        <th>Remove</th>
			</tr>
		</thead>
		<tbody class="body-half-screen">
    {% if answer %}
		{% for ans in answer %}
			<tr>
				<td style="padding-right: 100px; width: 0px;">{{ans.answer}}</td>
				<td>{{ans.question}}</td>
				<td>
	      	<strong><button class="b1"><i class="fas fa-thumbs-up fa-1x"></i></button> {{ans.like.all.count}}</strong>
		    </td>
	      <td>{{ans.auth}}</td>
        <td><a href="{% url 'question:edit_answer' question_id=ans.question.id answer_id=ans.id %}"
          >Update</a>
        </td>
        <td>
          <a href="{% url 'question:remove_answer' question_id=ans.question.id answer_id=ans.id %}">
          Remove</a
          >
			</tr>
		{% endfor %}
    {% else %}
    <h1>No Answers!!</h1>
    {% endif %}
		</tbody>
	</table>
</div>

{% endblock %}