account/urls.py
from django.urls import path
from account.views import *
app_name = "account"

urlpatterns = [
    path('', home_view, name="home"),
    path('register/', register_view, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('account/<user_id>/', account_view, name="view"),
    path('account/<user_id>/edit/', edit_account_view, name="edit"),
    path('search/', account_search_view, name="search"),
    path('contect/', contect_view, name="contect"),
    path('aboutus/', about_us_view, name="about_us"),
]

kmarket/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace='account')),
    path('question/', include('question.urls', namespace='question')),
    path('notification/', include('notification.urls', namespace='notification')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),

    #     path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
    #          name='password_reset_done'),

    #     path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
    #          name='password_reset_confirm'),
    #     path('password_reset/', auth_views.PasswordResetView.as_view(),
    #          name='password_reset'),

    #     path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
    #          name='password_reset_complete'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset/password_reset.html",success_url=reverse_lazy('password_reset_done')), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset/password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset/password_reset_form.html",success_url=reverse_lazy('password_reset_complete')), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset/password_reset_done.html"), name="password_reset_complete"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notification/urls.py
from notification.views import *
from django.urls import path
from notification.models import Notification
app_name = "notification"

urlpatterns = [
    path('', ShowNOtification, name="show_notification"),
    path('<noti_id>/delete/', DeleteNotification, name="delete_notification"),
]

notification/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from account.models import Account
# Create your models here.


class Notification(models.Model):
    NOTIFICATION_TYPES = (
        (1, 'Like'),
        (2, 'LikeQuestion'),
        (3, 'Answer'),
    )
    question = models.ForeignKey(
        'question.Question', on_delete=models.CASCADE, related_name="noti_ques", blank=True, null=True)
    answer = models.ForeignKey('question.Answer', on_delete=models.CASCADE,
                               related_name="noti_ans", blank=True, null=True)
    sender = models.ForeignKey(
        Account, on_delete=models.CASCADE, related_name="noti_from_user")
    receiver = models.ForeignKey(
        Account, on_delete=models.CASCADE, related_name="noti_to_user")
    notification_type = models.CharField(
        choices=NOTIFICATION_TYPES, max_length=10)
    text_preview = models.CharField(max_length=100, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    is_seen = models.BooleanField(default=False)

notification/views.py
from django.shortcuts import render, redirect
from notification.models import Notification
# Create your views here.


def ShowNOtification(request, *args, **kwargs):
    user = request.user
    context = {}
    if not user.is_authenticated:
        return redirect("account:login")
    notifications = Notification.objects.filter(
        receiver=user).order_by('-date')
    Notification.objects.filter(receiver=user, is_seen=False).update(is_seen=True)
    context = {'notifications': notifications}
    return render(request, 'notification/notify.html', context)

def DeleteNotification(request, *args, **kwargs):
	user = request.user
	noti_id = kwargs.get("noti_id")
	notification = Notification.objects.filter(id=noti_id)
	notification.delete()
	return redirect('notification:show_notification')


def CountNotification(request):
	count_notifications = 0;
	if request.user.is_authenticated:
		count_notifications = Notification.objects.filter(receiver=request.user, is_seen=False).count()

	return {'count_notifications': count_notifications}

notification/templates/notification/notify.html
{% extends 'account/main.html' %} {% load static %} {% block content %}

<style type="text/css">
  .main {
    border-radius: 25px;
    height: -webkit-fit-content;
    height: -moz-fit-content;
    height: fit-content;
    /* display: inline-flex; */
    background-color: rgba(0, 0, 0, 0.4);
    -webkit-backdrop-filter: blur(10px);
    backdrop-filter: blur(10px);
    width: 35cm;
    height: 13cm;
    margin-top: 1.3cm;
    margin-left: 2.8cm;
    padding-bottom: 3.5em;
    align-items: center;
  }
  .images {
    border-radius: 15px;
    width: 80px;
    height: 80px;
  }

  .table-scroll {
    /*width:100%; */
    display: block;
    /* empty-cells: show; */
    width: 33cm;
    margin-left: 1cm;
    /*padding-top: 1cm;*/
    /* Decoration */
    border-spacing: 0;
    margin-top: -50px;
    /* border: rgba(130, 130, 170, 0.1); */
  }

  .table-scroll tbody {
    border-radius: 15px;
    /* Position */
    align-items: center;
    display: block;
    position: relative;
    width: 100%;
    height: 6.3cm;
    padding-bottom: 3cm;
    overflow-y: scroll;
    /* Decoration */
    border-top: 1px solid rgba(0, 0, 0, 0.2);
  }

  .table-scroll tr {
    width: 100%;
    display: flex;
  }

  .table-scroll td,
  .table-scroll th {
    flex-basis: 100%;
    flex-grow: 2;
    display: block;
    padding: 1rem;
    text-align: left;
    margin-left: 10px;
    /*align-items: center;*/
  }

  /* Other options */

  .table-scroll.small-first-col td:first-child,
  .table-scroll.small-first-col th:first-child {
    flex-basis: 20%;
    flex-grow: 1;
  }

  .table-scroll tbody tr:nth-child(2n) {
    background-color: rgba(130, 130, 170, 0.1);
  }

  .body-half-screen {
    max-height: 50vh;
  }

  .small-col {
    flex-basis: 10%;
  }

  .table-scroll ::-webkit-scrollbar {
    width: 6px;
  }
  .table-scroll ::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
  }
  .table-scroll ::-webkit-scrollbar-thumb {
    -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
  }
  /*#noti-text{
    margin-bottom: 20px;
  }*/
  h1 {
    padding-top: 30px;
    margin-left: 40px;
    margin-bottom: 0px;
  }
</style>

<div class="main">
  <h1>Notifications</h1>
  <table class="table-scroll small-first-col">
    <tbody>
      {% if notifications %} 
        {% for notification in notifications %} 
          {% if notification.notification_type == '3' %}
          <tr>
            <td>
              <img
                src="{{notification.sender.profile_image.url}}"
                style="width: 100px; height: 100px"
              />
            </td>
            <td>
              <strong id="noti-text">
                {{notification.sender.username}} Answered your Question
                <a
                  href="{% url 'notification:delete_notification' noti_id=notification.id %}"
                  class="delete btn-danger"
                  ><i class="fas fa-trash-alt"></i></a>
                <br />
              </strong>
              <strong style="overflow: hidden" id="noti-text">
                Question: {{notification.question}} <br />
              </strong>
              <strong id="noti-text"> {{notification.date}} </strong>
            </td>
            <br />
          </tr>
          {% endif %} 
          {% if notification.notification_type == '2' %}
          <tr>
            <td>
              <img
                src="{{notification.sender.profile_image.url}}"
                style="width: 100px; height: 100px"
              />
            </td>
            <td>
              <strong id="noti-text">
                {{notification.sender.username}} Liked your Question
                <a
                  href="{% url 'notification:delete_notification' noti_id=notification.id %}"
                  class="delete btn-danger"
                  ><i class="fas fa-trash-alt"></i></a>
                <br />
              </strong>
              <strong style="overflow: hidden" id="noti-text">
                Question: {{notification.question}}<br />
              </strong>
              <strong id="noti-text">{{notification.date}}</strong>
            </td>
            <br />
          </tr>
          {% endif %} 
          {% if notification.notification_type == '1' %}
          <tr>
            <td>
              <img
                src="{{notification.sender.profile_image.url}}"
                style="width: 100px; height: 100px"
              />
            </td>
            <td>
              <strong id="noti-text">
                {{notification.sender.username}} Liked your Answer
                <a
                  href="{% url 'notification:delete_notification' noti_id=notification.id %}"
                  class="delete btn-danger"
                  ><span class="input-group-text" id="basic-addon1"
                    ><i class="fas fa-trash-alt"></i></span
                ></a>
                <br />
              </strong>
              <strong style="overflow: hidden" id="noti-text">
                Answer: {{notification.answer}}<br />
              </strong>
              <strong id="noti-text">{{notification.date}}</strong>
            </td>
            <br />
          </tr>
          {% endif %} 
        {% endfor %} 
      {% else %}
      <h1>No Notifications!!</h1>
      {% endif %}
    </tbody>
  </table>
</div>

{% endblock %}